### ISSUE TITLE
Does not work with ruby-saml > 1.9

### ISSUE THREAD

**Issue by gsmetal** [flant/simple_saml#1]
Error: 
```NoMethodError
undefined method `single_signon_service_binding' for #<OneLogin::RubySaml::IdpMetadataParser:0x0000000003ee0a18>
```
Ruby-saml change: https://github.com/onelogin/ruby-saml/commit/e36442fba5072194d09a9bacebc82e6469c4a300
